metrics:
- name: "DCGM_FI_DEV_GPU_UTIL"
  type: "gauge"
  utilizationPattern:
    # write a steady value
    steady:
      value: 7.0
    # write a random value
    random:
      max: 100.0
      min: 1.0
    # oscillate between 2 values rapidly
    oscillating:
      sustainValue: 100.0
      minValue: 1.0
      minCount: 1
      sustainCount: 1
      dropSteps: 1
      riseSteps: 1
    # oscillate between 2 values, sustained high then cliff drop then rise back to sustained high
    oscillating:
      sustainValue: 100.0
      minValue: 10.0
      minCount: 3
      sustainCount: 10
      dropSteps: 3
      riseSteps: 1
    # oscillate between 2 values, sustained low then spike up then drop back to sustained low
    oscillating:
      sustainValue: 10.0
      minValue: 100.0
      minCount: 3
      sustainCount: 10
      dropSteps: 3
      riseSteps: 1
  labels:
  - node: edge-ffa238429efe572a777ef4a17e4fd9b7
  interval: 1s
