metrics:
- name: "DCGM_FI_DEV_GPU_UTIL"
  type: "gauge"
  utilizationPattern:
    # write a steady value
    steady:
      value: 7.0
    # write a random value
    random:
      max: 100.0
      min: 1.0
    # oscillate between 2 values rapidly
    oscillating:
      y1: 100.0
      y1Count: 1
      y2: 1.0
      y2Count: 1
      y1y2StepCount: 0
      y2y1StepCount: 0
    # oscillate between 2 values, sustained high then cliff drop then jump back up to sustained high
    oscillating:
      y1: 100.0
      y1Count: 10
      y2: 10.0
      y2Count: 3
      y1y2StepCount: 5
      y2y1StepCount: 0
    # oscillate between 2 values, sustained low then spike up then drop back to sustained low
    oscillating:
      y1: 10.0
      y1Count: 10
      y2: 100.0
      y2Count: 3
      y1y2StepCount: 5
      y2y1StepCount: 0
  labels:
  - node: edge-ffa238429efe572a777ef4a17e4fd9b7
  interval: 5s
  jitter: 2s # default: 0s
