global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

# Note: out_of_order_time_window is required if using `time machine` to allow for concurrent metric writes in the past and present.
storage:
  tsdb:
    out_of_order_time_window: 1d
